services:
  php:
    build:
      context: ./php
    container_name: php-fpm
    volumes:
      - ./php:/var/www/html
      - ./php/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf
    depends_on:
      - mongo
      - elasticsearch
    healthcheck:
      test: ["CMD", "curl", "-f", "http://nginx:8080/status"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
    healthcheck:
      test: ["CMD", "curl", "-f", "http://nginx:8080/server_status"]
      interval: 30s
      timeout: 10s
      retries: 3

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  elasticsearch:
    image: elasticsearch:7.17.12
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      influxdb:
        condition: service_healthy
      php:
        condition: service_started
      nginx:
        condition: service_started
    restart: always


  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=telegraf
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin123
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/ping"]
      interval: 5s
      retries: 5
      start_period: 10s
    restart: always

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/prov/:/etc/grafana/provisioning/
      - ./grafana/dashboards/:/var/lib/grafana/dashboards/
    depends_on:
      - influxdb

volumes:
  influxdb_data: {}
  mongodb_data: {}
  elasticsearch_data: {}
  grafana_data: {}
